"""add user_timezone field for users

Revision ID: 3cea95741e2f
Revises: c519965d11ee
Create Date: 2025-08-13 21:26:53.543247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cea95741e2f'
down_revision: Union[str, Sequence[str], None] = 'c519965d11ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_timezone')
    # ### end Alembic commands ###
