"""Remove underscores from field names

Revision ID: 433c3d78b51e
Revises: 85b9c6775d36
Create Date: 2025-09-02 18:43:19.913630

"""
# This is done for better command perfomance
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433c3d78b51e'
down_revision: Union[str, Sequence[str], None] = '85b9c6775d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phonenumber', sa.String(length=19), nullable=True))
    op.add_column('users', sa.Column('books', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('films', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('games', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('music', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('remindtime', sa.Interval(), nullable=True))
    op.drop_column('users', 'remind_time')
    op.drop_column('users', 'favorite_games')
    op.drop_column('users', 'favorite_music')
    op.drop_column('users', 'favorite_books')
    op.drop_column('users', 'favorite_films')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=19), nullable=True))
    op.add_column('users', sa.Column('favorite_films', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('favorite_books', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('favorite_music', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('favorite_games', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('remind_time', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'remindtime')
    op.drop_column('users', 'music')
    op.drop_column('users', 'games')
    op.drop_column('users', 'films')
    op.drop_column('users', 'books')
    op.drop_column('users', 'phonenumber')
    # ### end Alembic commands ###
