"""Add reminder_time field to users

Revision ID: 5b5523af8324
Revises: 3cea95741e2f
Create Date: 2025-08-15 23:06:43.243077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5523af8324'
down_revision: Union[str, Sequence[str], None] = '3cea95741e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remind_time', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remind_time')
    # ### end Alembic commands ###
