"""Add ondelete options

Revision ID: 5ef2b2b9b961
Revises: 17549c71fb59
Create Date: 2025-09-20 19:30:08.314560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef2b2b9b961'
down_revision: Union[str, Sequence[str], None] = '17549c71fb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_lessons_student_id_users'), 'users', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_unit_id_units'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_unit_id_units'), 'units', ['unit_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_answer_id_words'), 'words', ['answer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_units_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_units_book_id_books'), 'books', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_units_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_units_book_id_books'), 'books', ['book_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_answer_id_words'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_unit_id_units'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_unit_id_units'), 'units', ['unit_id'], ['id'])
        batch_op.create_foreign_key(None, 'words', ['answer_id'], ['id'])

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lessons_student_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###
