"""Add MtM for Word-Tranclation

Revision ID: 85b9c6775d36
Revises: ad07c6dbb30d
Create Date: 2025-08-31 22:21:32.079019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b9c6775d36'
down_revision: Union[str, Sequence[str], None] = 'ad07c6dbb30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_mtm_translation',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'translation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_mtm_translation')
    # ### end Alembic commands ###
