"""Add task model

Revision ID: ad07c6dbb30d
Revises: fb3e562343dd
Create Date: 2025-08-30 15:28:17.465556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad07c6dbb30d'
down_revision: Union[str, Sequence[str], None] = 'fb3e562343dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lessons', sa.Column('duration', sa.Interval(),
                                       nullable=False))
    op.add_column('users', sa.Column('points', sa.SmallInteger(),
                                     nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points')
    op.drop_column('lessons', 'duration')
    op.drop_table('tasks')
    # ### end Alembic commands ###
