"""Add books and units

Revision ID: b78f56ea2660
Revises: 433c3d78b51e
Create Date: 2025-09-16 19:44:04.305663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78f56ea2660'
down_revision: Union[str, Sequence[str], None] = '433c3d78b51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    op.create_table('units',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_units_book_id_books')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units'))
    )
    op.create_table('word_mtm_unit',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_word_mtm_unit_unit_id_units')),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('fk_word_mtm_unit_word_id_words')),
    sa.PrimaryKeyConstraint('word_id', 'unit_id', name=op.f('pk_word_mtm_unit'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_unit_id_units'), 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_users_book_id_books'), 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_book_id_books'), type_='foreignkey')
        batch_op.drop_column('book_id')
        batch_op.drop_column('price')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_unit_id_units'), type_='foreignkey')
        batch_op.drop_column('unit_id')

    op.drop_table('word_mtm_unit')
    op.drop_table('units')
    op.drop_table('books')
    # ### end Alembic commands ###
