# DB values:
MAX_NAME_LEN = 50
MAX_PHONE_NUMBER_LEN = 19
MAX_USERNAME_LEN = 32

# User roles:
ADMIN, DEV, STRANGER, STUDENT = 'admin', 'dev', 'stranger', 'student'
STAFF = (ADMIN, DEV)
USER_ROLES = STAFF + (STRANGER, STUDENT)
